name: Unzip and Build Android

on:
  push:
    paths:
      - "q.zip"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip q.zip
        run: |
          unzip -o q.zip -d extracted
          shopt -s dotglob
          INNER=$(find extracted -mindepth 1 -maxdepth 1 -type d | head -n1)
          if [ -n "$INNER" ]; then mv "$INNER"/* . ; else mv extracted/* . ; fi
          rm -rf extracted q.zip

      - name: Show structure
        run: ls -R | head -100

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle wrapper (if missing)
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
