name: Unzip project

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Buscar ZIP
        run: |
          ZIPFILE=$(ls *.zip 2>/dev/null || true)
          if [ -z "$ZIPFILE" ]; then
            echo "❌ No se encontró ningún .zip en la raíz del repo"
            exit 1
          fi
          echo "ZIPFILE=$ZIPFILE" >> $GITHUB_ENV
          echo "Encontrado: $ZIPFILE"

      - name: Descomprimir
        run: |
          unzip -o "$ZIPFILE" -d __extracted
          rsync -a __extracted/ ./ --exclude ".git/" --exclude "__extracted/"
          rm -rf __extracted "$ZIPFILE"

      - name: Commit descompresión
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Descomprimir $ZIPFILE en raíz del repo"
            git push
          else
            echo "ℹ️ Nada que commitear"
          fi
